### ISSUE TITLE
Missing class

### ISSUE THREAD

**Issue by tomjur** [CognitiveAISystems/MAPF-GPT#3]
Hi,

Is the following reference from train.py is missing?

from gpt.fast_data_loader import MapfArrowDataset

There is no corresponding file fast_fata_loader under gpt.

Thanks,
Tom

**Comment by Tviskaron** [comment]
Oh, I somehow missed adding the file. Thanks for catching that! Fixed in 58079e8.

**Comment by tomjur** [comment]
Thanks for the quick response 🙏
