### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by linhlt-it-ee** [CognitiveAISystems/MAPF-GPT#4]
Helllo, how to do inference with MAPF-gpt if I have the map array, positions of agents and obstacles of the map?

**Comment by Tviskaron** [comment]
Hello! You can set up your scenario using POGEMA, which allows you to specify the positions of agents, targets, and obstacles on the map. If you encounter any issues, feel free to ask for help!

**Comment by linhlt-it-ee** [comment]
Hello Tviskaron,
I only see this, but no other instruction to assign the values of agents' positions and the targets' positions? Can u pls give me some details for this.
from pogema import pogema_v0, GridConfig

grid = """
.....#.....
.....#.....
...........
.....#.....
.....#.....
#.####.....
.....###.##
.....#.....
.....#.....
...........
.....#.....
"""

# Define new configuration with 8 randomly placed agents
grid_config = GridConfig(map=grid, num_agents=8)

# Create custom Pogema environment
env = pogema_v0(grid_config=grid_config)

**Comment by linhlt-it-ee** [comment]
I'm working with pogema_vo, and I've noticed that it doesn't have a save_animation function. What would be the best alternative to achieve similar functionality?

Additionally, I'm encountering an "out of bounds" error with the following setup:


env = pogema_vo(grid_config=GridConfig(agents_xy=agents_xy, targets_xy=targets_xy, map=grid_map))
The map size is (32, 32), and I've ensured that no agent or target has a position index greater than or equal to 32. What could be causing this issue, and how can I fix it?

**Comment by linhlt-it-ee** [comment]
also this error:   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for GridConfig
map
  Mismatch in number of agents and targets. (type=assertion_error)

**Comment by Tviskaron** [comment]
I believe this [notebook](https://colab.research.google.com/drive/19dSEGTQeM3oVJtVjpC162t1XApmv6APc?usp=sharing#scrollTo=zlu8ouRH46OF) from readme.md should help you. It provides both an example of using animation monitor and an example of creating custom scenarios in POGEMA

**Comment by Tviskaron** [comment]
@linhlt-it-ee
